### ISSUE TITLE
figure out why `EpiEstim` throws "too early" warning and intercept it with a more helpful warning

### ISSUE THREAD

**Issue by papsti** [phac-nml-phrsd/ern#117]
see [side note](https://github.com/phac-nml-phrsd/ern/issues/114#issuecomment-1472068893) in #114... we should figure out exactly what about the example data in that issue provoked the warning from `EpiEstim` (along with the bogus $R_t$ estimates) and use that info to write a more descriptive warning for the user that explains what happened and how it could be remedied

**Comment by davidchampredon** [comment]
This message disappears when adjusting the date ranges fed into `ern::estimate_R_cl/ww()`. The warning appears when the time series input is "flat" with few cases at the beginning. `EpiEstim` expects more variability in the data (i think this is to comply with some assumption of its underlying statistical model). I think we should not intercept the warning and leave it to the user to decide what to do based on `EpiEstim`'s behaviour, because ultimately this is the engine we are using.

**Comment by papsti** [comment]
i agree that we shouldn't intercept the warning, but given that this was non-trivial for us to figure out, do you think it would be possible to detect when this exact warning is produced by EpiEstim and add our own guidance after it (_e.g._ tell them the time series input is flat with few cases at the beginning, so they should try to adjust the estimation date range)? one question is whether we can think of a good technical way to amend the warning, and another is if this EpiEstim warning is specific enough to this case that our additional guidance will always make sense.

**Comment by davidchampredon** [comment]
Let's leave the native `EpiEstim` warning for now and let the user figure it out (as it would be if the user used `EpiEstim` directly...)
